# Generated by Django 6.0.4 on 2026-07-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
