# Generated by Django 6.0.4 on 2026-07-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_job_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
