# Generated by Django 6.0.4 on 2026-07-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_job_owner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner_email',
        ),
    ]
