# Generated by Django 6.0.4 on 2026-07-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_job_owner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
    ]
