# Generated by Django 6.0.4 on 2026-07-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_job_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(default='Any', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default='Any', max_length=20),
        ),
    ]
