# Generated by Django 6.0.4 on 2026-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_job_education_job_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
