# Generated by Django 6.0.4 on 2026-07-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_activitylog_dob_activitylog_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
