# Generated by Django 6.0.4 on 2026-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_activitylog_dob_remove_activitylog_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shop_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_photos/'),
        ),
    ]
